# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: gemini_server 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "gemini_server".freeze
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Jess Bees".freeze]
  s.date = "2020-11-16"
  s.description = "".freeze
  s.email = "hi@toomanybees.com".freeze
  s.files = [
    "Gemfile",
    "VERSION",
    "lib/gemini_server.rb",
    "lib/gemini_server/mime_types.rb",
    "lib/gemini_server/responses.rb"
  ]
  s.homepage = "http://github.com/TooManyBees/gemini_server".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.1.4".freeze
  s.summary = "Simple server for the Gemini protocol".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4
  end

  if s.respond_to? :add_runtime_dependency then
    s.add_runtime_dependency(%q<addressable>.freeze, ["~> 2.7"])
    s.add_runtime_dependency(%q<async-io>.freeze, ["~> 1.30"])
    s.add_runtime_dependency(%q<mime-types>.freeze, ["~> 3.3"])
    s.add_runtime_dependency(%q<mustermann>.freeze, ["~> 1.1"])
    s.add_development_dependency(%q<juwelier>.freeze, ["~> 2.4.9"])
  else
    s.add_dependency(%q<addressable>.freeze, ["~> 2.7"])
    s.add_dependency(%q<async-io>.freeze, ["~> 1.30"])
    s.add_dependency(%q<mime-types>.freeze, ["~> 3.3"])
    s.add_dependency(%q<mustermann>.freeze, ["~> 1.1"])
    s.add_dependency(%q<juwelier>.freeze, ["~> 2.4.9"])
  end
end

